<a href="https://colab.research.google.com/github/rohitsa10/SIMATS-PROGRAM-ML/blob/main/co5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LAB EXPERIMENT 1: Rule-Based Learning using Sequential Covering Algorithm

In [2]:
# Simple Sequential Covering Algorithm
data = [
    ['Sunny','Hot','High','Weak','No'],
    ['Sunny','Hot','High','Strong','No'],

    ['Overcast','Hot','High','Weak','Yes'],
    ['Rain','Mild','High','Weak','Yes']
]
rules = []
for row in data:
    if row[-1] == 'Yes':
        rule = row[:-1]
        rules.append(rule)
print("Learned Rules:")
for r in rules:
    print("IF", r, "THEN Yes")

Learned Rules:
IF ['Overcast', 'Hot', 'High', 'Weak'] THEN Yes
IF ['Rain', 'Mild', 'High', 'Weak'] THEN Yes


LAB EXPERIMENT 2: Learning Rule Sets using Decision Tree Rule Extraction

In [4]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier, export_text
X, y = load_iris(return_X_y=True)
model = DecisionTreeClassifier(max_depth=3)
model.fit(X, y)
rules = export_text(model)
print("Extracted Rules:\n")
print(rules)

Extracted Rules:

|--- feature_2 <= 2.45
|   |--- class: 0
|--- feature_2 >  2.45
|   |--- feature_3 <= 1.75
|   |   |--- feature_2 <= 4.95
|   |   |   |--- class: 1
|   |   |--- feature_2 >  4.95
|   |   |   |--- class: 2
|   |--- feature_3 >  1.75
|   |   |--- feature_2 <= 4.85
|   |   |   |--- class: 2
|   |   |--- feature_2 >  4.85
|   |   |   |--- class: 2



LAB EXPERIMENT 3: Explanation-Based Learning (EBL)

In [6]:
# Simple Explanation-Based Learning Example
def is_safe(temp, fuel):
    return temp < 100 and fuel > 50
example = {'temp': 80, 'fuel': 60}
if is_safe(example['temp'], example['fuel']):
    rule = "IF temperature < 100 AND fuel > 50 THEN SAFE"
    print("Learned Rule:", rule)

Learned Rule: IF temperature < 100 AND fuel > 50 THEN SAFE


LAB EXPERIMENT 4: Reinforcement Learning – Q-Learning Algorithm

In [8]:
import numpy as np
states = 5
actions = 2
Q = np.zeros((states, actions))
alpha = 0.1
gamma = 0.9
for episode in range(100):
    state = 0
    while state < states - 1:
        action = np.argmax(Q[state])
        next_state = state + 1

        reward = 1 if next_state == states - 1 else 0
        Q[state, action] += alpha * (reward + gamma * np.max(Q[next_state]) - Q[state, action])
        state = next_state
print("Q-Table:\n", Q)

Q-Table:
 [[0.7232872  0.        ]
 [0.80842464 0.        ]
 [0.89971048 0.        ]
 [0.99997344 0.        ]
 [0.         0.        ]]


LAB EXPERIMENT 5: Reinforcement Learning – Grid World Optimization

In [10]:
import numpy as np
grid = np.zeros((3,3))
Q = np.zeros((9,4))

def next_state(state, action):
    row, col = divmod(state, 3)
    if action == 0 and row > 0: row -= 1
    if action == 1 and row < 2: row += 1
    if action == 2 and col > 0: col -= 1
    if action == 3 and col < 2: col += 1
    return row*3 + col

for _ in range(200):
    s = 0
    while s != 8:
        a = np.random.randint(4)
        ns = next_state(s, a)
        reward = 1 if ns == 8 else -0.01
        Q[s,a] += 0.1 * (reward + 0.9 * np.max(Q[ns]) - Q[s,a])
        s = ns
print("Optimized Q-Values:\n", Q)

Optimized Q-Values:
 [[0.62149431 0.70175328 0.62150132 0.70175125]
 [0.70171423 0.79088171 0.62148892 0.79086262]
 [0.79083796 0.88992804 0.70162312 0.79067317]
 [0.62144601 0.7907952  0.70173343 0.79087912]
 [0.70155469 0.88983986 0.70164823 0.88992252]
 [0.78979474 0.99998432 0.78982308 0.88944169]
 [0.70162059 0.79044278 0.79046777 0.88986603]
 [0.79032357 0.88832237 0.7901088  0.99995502]
 [0.         0.         0.         0.        ]]
